name: My first action

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Greetings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: echo "Hello World!"