name: My first action

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Greetings
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v2`
      - run: echo "Hello World!"