name: My first action

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Greetings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World!"
      - run: mkdir Plop
      - run: ls -a > redirect
      - run: mv redirect Plop/
      - run: ls Plop