name: Compilation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./app/c/
      - run: make