name: Multi OS

on:
  push:
    branches:
      - main
    commit-ignore:
      - [skip ci]

jobs:
  main:
    name: WinduntuOS
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello from ${{ matrix.os }}"
