name: Hello_python

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Greetings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
      cd app/python
      python3 hello.py